BACKEND_BASE_URL = "http://127.0.0.1:8080"
STUDENT_REGISTRTION_ENDPOINT = "/register/student_register"
USER_LOGIN_ENDPOINT = "/user/login"
FILE_PATH = "/home/mukesh/access_token/"
EMPLOYEE_REGISTARTOIN_ENDPOINT = "/register/employee_register"